# -----------------------------------------------------------------------------
# Dockerfile for testing libnss-extrausers-rpm_rockylinux 
# -----------------------------------------------------------------------------

ARG BASE_RELEASE=9
ARG BASE_IMAGE=rockylinux
ARG TEST_IMAGE=ghcr.io/abcdesktopio/libnss-extrausers-rpm_rockylinux

# IMAGE_SOURCE is the container image with the RPM package 
FROM ${TEST_IMAGE} AS IMAGE_SOURCE

FROM ${BASE_IMAGE}:${BASE_RELEASE}
RUN  dnf install -y diffutils
COPY --from=IMAGE_SOURCE /root/rpmbuild/RPMS/*/libnss-extrausers*.rpm /
RUN rpm -i /*.rpm
COPY passwd group shadow /var/lib/extrausers
COPY nsswitch.conf /etc/nsswitch.conf
COPY result.expected /
RUN id fry > result.done
RUN diff result.done /result.expected
CMD ["bash"]
